# Using official python runtime base image
FROM python:2.7-alpine

# Set the application directory
WORKDIR /app

# Install our requirements.txt
ADD requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Copy our code from the current folder to /app inside the container
ADD . /app

RUN --mount=type=secret,id=GRAPHQL_PRO_CREDENTIAL cat /run/secrets/GRAPHQL_PRO_CREDENTIAL
RUN --mount=type=secret,id=TEST_OTHER cat /run/secrets/TEST_OTHER

# Make port 80 available for links and/or publish
EXPOSE 80

# Define our command to be run when launching the container
CMD ["gunicorn", "app:app", "-b", "0.0.0.0:80", "--log-file", "-", "--access-logfile", "-", "--workers", "4", "--keep-alive", "0"]
